### PR TITLE
Calendar dev bug fix with wrong dates and test updates

### PR DESCRIPTION
**Pull request by alaguelo**
- fix bugs with faded dates being wrong
- updated some tests, still work in progress

### CODE REVIEW

**Review by mic051 — APPROVED** [review]
Looks good. Merge new calendar functionality, fixed calendar dates, new tests. Looks like nothing old got deleted

**Review by darischen — APPROVED** [review]
Updated Tests, Fixed Bugs with Faded Dates, Linked Journal with Calendar

**Review by darischen — APPROVED** [review]
Fixed Local Merge Issues

**Review by darischen — APPROVED** [review]
Package.json devDependencies Updated

**Review by darischen — APPROVED** [review]
Test File Appears

**Comment by darischen** [comment]
We changed a lot of files to get the unit tests on github actions to work, be careful as we don't know if it will affect other branches as well.

**Review by darischen — APPROVED** [review]
Popup Functions

**Pull request merged**
